version: 2

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - sphinx
        - breathe
        - exhale
        - myst-parser
        - sphinx-book-theme

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - pip install sphinx exhale myst-parser sphinx-book-theme
    - sed s,\${PROJECT_SOURCE_DIR},$(pwd),g Doxyfile.in > Doxyfile
    - doxygen Doxyfile
    - cd docs && make html
    - pwd
    - ls -R .
    - cp -r build/html $READTHEDOCS_OUTPUT/html/  
