version: 2

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - sphinx
        - breathe
        - exhale
        - myst-parser
        - sphinx-book-theme

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"

conda:
  environment: environment.yaml

build:
  commands:
    - sed 's/\$\{PROJECT_SOURCE_DIR\}/$(pwd)/g' Doxyfile.in
    - mkdir build        
    - cd build
    - cmake .. -DCMAKE_PREFIX_PATH=/usr/local -DBUILD_LIB=OFF -DBUILD_DOCUMENTATION=ON         
    - cd ../docs 
    - make html
    - cp -r build/html $READTHEDOCS_OUTPUT/html/  
