version: 2

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - sphinx
        - breathe
        - exhale
        - myst-parser
        - sphinx-book-theme

conda:
  environment: environment.yaml

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"
  commands:
    - pwd
    - conda env create --name build --file environment.yaml
    - conda init bash
    - conda activate build
    - mkdir build        
    - cd build
    - cmake .. -DCMAKE_PREFIX_PATH=/usr/local -DBUILD_LIB=OFF -DBUILD_DOCUMENTATION=ON         
    - cd ../docs 
    - make html
    - cp -r build/html $READTHEDOCS_OUTPUT/html/  
