version: 2

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - sphinx
        - breathe
        - exhale
        - myst-parser
        - sphinx-book-theme

build:
  os: ubuntu-22.04
  commands:
    - sed s/\${PROJECT_SOURCE_DIR}/$(pwd | sed 's/\//\\\//g')/g Doxyfile.in > Doxyfile
    - doxygen -g Doxyfile
    - cd docs
    - make html
    - cp -r build/html $READTHEDOCS_OUTPUT/html/  
